### PR TITLE
Return display string + tests

### PR DESCRIPTION
**Pull request by matiasdelgado**
@patrickkettner this is a fix for an issue in which the generated manifest.json has the `display` attribute set to true rather the a valid string (`fullscreen`, `standalone`, `minimal-ui`, `browser`).
The default value (browser) was the only returned as a string.

I changed the display scraper, this line in particular: `const _display = fullscreen || standalone || minimal || 'browser';`.
Unit tests added for the display scraper. 

Comments and suggestions are welcome :)

### CODE REVIEW

**Comment by patrickkettner** [comment]
Hey @matiasdelgado!
Thanks a ton for reaching out. I'd really like to get it merged, however I am not interested in the dot files (note that this project wouldn't be affected by nearly any of them). If you could pull those out I'l get this merged and released asap

**Comment by matiasdelgado** [comment]
It's done. Thanks for the feedback, and let me know if I can help with anything else.

**Comment by patrickkettner** [comment]
thanks a ton!

**Comment by patrickkettner** [comment]
published in 2.0.9

**Pull request merged**
